// reportbugs.h

/*
  reportbugs.o is automatically generated by txtc.sh
*/

#ifndef _REPORTBUGS_H
#define _REPORTBUGS_H

extern int reportbugs_text_length ;
extern char *reportbugs_text[] ;

#endif // _REPORTBUGS_H
