.TH SOURCE-HIGHLIGHT-SETTINGS "1" "May 2009" "Source-highlight-settings" "User Commands"
.SH NAME
Source-highlight-settings \- utility that can be used to write a configuration file for GNU Source\-highlight (and its library)
.SH SYNOPSIS
.B source-highlight-settings
.SH DESCRIPTION
Since version 3.0, GNU Source\-highlight includes also the utility source\-highlight\-settings, which can be used to check whether source\-highlight will be able to find its language definition files, and other configuration files, and in case, to store the correct settings in a configuration file, in the user home directory.
.PP
In particular, the stored configuration file will be called source\-highlight.conf and will be stored in $HOME/.source\-highlight/.
.PP
For the moment, this file only stores the default value for the \-\-data\-dir option. 
.PP
This utility is part of GNU Source-highlight, maintained by:
.br
Lorenzo Bettini <http://www.lorenzobettini.it>
.SH "REPORTING BUGS"
Report bugs to <bug\-source\-highlight at gnu.org>
.SH COPYRIGHT
Copyright \(co 1999-2009 Lorenzo Bettini <http://www.lorenzobettini.it>
This program comes with ABSOLUTELY NO WARRANTY.
.br
This is free software; you may redistribute copies of the program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
.SH "SEE ALSO"
The full documentation for
.B source-highlight
is maintained as a Texinfo manual.  If the
.B info
and
.B source-highlight
programs are properly installed at your site, the command
.IP
.B info source-highlight
.PP
should give you access to the complete manual.
