// copyright.h

/*
  copyright.o is automatically generated by txtc.sh
*/

#ifndef _COPYRIGHT_H
#define _COPYRIGHT_H

extern int copyright_text_length ;
extern char *copyright_text[] ;

#endif // _COPYRIGHT_H
